# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da87eb47a85d1d157773bbc918a4e18133ca13c6526bbe6ce547d1e1013cc637a2e360e4ff0053a9065b910c51b3e8768709b95fad767dc551cffa8d2e8b3b99

test:
  secret_key_base: 55fd6d3109bf21c4c9c3d9194be66d97d4c2da374d813c656adaf0ccf91f17d13c385e76a7d5d9f0964c7d5f8c5c76a10fd9e37cdfb04525e56f370ac7917f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
